prose:
  rooturl: 'contributions'
  media: 'media'
  metadata:
    contributions:
      - name: "author"
        field:
          element: "text"
          label: "Contributeurs"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Titre"
          value: "Contribution multibao"
      - name: "description"
        field:
          element: "textarea"
          label: "Courte description"
          value: ""
      - name: "caption"
        field:
          element: "textarea"
          label: "Lien vers l'image"
          value: ""
