prose:
  rooturl: 'contributions'
  media: 'media'
  metadata:
    contributions:
      - name: "author"
        field:
          element: "text"
          label: "Contributeurs"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Titre"
          value: "Contribution multibao"
      - name: "description"
        field:
          element: "textarea"
          label: "Courte description"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Mots clés (max 5)"
          placeholder: "Choisir des tags"
          options:
            - name: "Ice breaker"
              value: "Ice breaker"
            - name: "Energizer"
              value: "Energizer"
            - name: "Organisation"
              value: "Organisation"
            - name: "Collaboration"
              value: "Collaboration"
            - name: "Citoyenneté"
              value: "Citoyenneté"
